### ISSUE TITLE
Not working on Linux / Fedora 38

### ISSUE THREAD

**Issue by NemoCZmoravia** [Toocanzs/anki-voicevox#2]
When I try to generate audio on Fedora 38, flatpak Anki I get this error:

> Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.5.5-200.fc38.x86_64-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-15 21:47:59
Add-ons possibly involved: ⁨VOICEVOX Japanese Text To Speech Audio Generator⁩

> Caught exception:
Traceback (most recent call last):
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/366960193/__init__.py", line 6, in <lambda>
    menu.addAction("Generate VOICEVOX Audio", lambda: voicevox_gen.onVoicevoxOptionSelected(browser))
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/366960193/voicevox_gen.py", line 399, in onVoicevoxOptionSelected
    new_audio_data = ffmpeg.ConvertWavToMp3(audio_data)
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/366960193/ffmpeg.py", line 87, in ConvertWavToMp3
    startupinfo = subprocess.STARTUPINFO()
AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'

I got the VOICEVOX running. I can even see the query going through, but it seems the add-on is what fails.

> INFO:     127.0.0.1:52550 - "GET /version HTTP/1.1" 200 OK
INFO:     127.0.0.1:52564 - "GET /speakers HTTP/1.1" 200 OK
INFO:     127.0.0.1:52570 - "POST /audio_query?speaker=2&text=%E3%81%9F%E3%81%8B%E3%81%84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52578 - "POST /multi_synthesis?speaker=2 HTTP/1.1" 200 OK

**Comment by Toocanzs** [comment]
I've just push a fix, download the latest version and please let me know if the problem still persists.
